name: Validate Schema

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate schema and check for changes
        run: |
          poetry run python -m scripts.generate_schema > schema.tmp.json
          if ! cmp -s schema.tmp.json schema.json; then
            echo "❌ schema.json is outdated. Run scripts/generate_schema.py and commit the updated file."
            exit 1
          fi
